def criar_tabelas(cursor):
    tabelas = [
        """
        CREATE TABLE IF NOT EXISTS `0000` (
            id INT AUTO_INCREMENT PRIMARY KEY,
            reg VARCHAR(4) DEFAULT '0000',
            cod_ver VARCHAR(3),
            cod_fin INT(1),
            dt_ini VARCHAR(8),
            dt_fin VARCHAR(8),
            nome VARCHAR(100),
            cnpj VARCHAR(14),
            cpf VARCHAR(11),
            uf VARCHAR(2),
            ie VARCHAR(20),
            cod_num VARCHAR(7),
            im VARCHAR(50),
            suframa VARCHAR(9),
            ind_perfil VARCHAR(1),
            ind_ativ VARCHAR(1),
            filial VARCHAR(4),
            periodo VARCHAR(10)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS c100 (
            id INT AUTO_INCREMENT PRIMARY KEY,
            periodo VARCHAR(10),
            reg CHAR(4) DEFAULT 'C100',
            ind_oper VARCHAR(1),
            ind_emit VARCHAR(1),
            cod_part VARCHAR(30),
            cod_mod VARCHAR(2),
            cod_sit INT(2),
            ser VARCHAR(3),
            num_doc VARCHAR(9),
            chv_nfe CHAR(44),
            dt_doc VARCHAR(8),
            dt_e_s VARCHAR(8),
            vl_doc VARCHAR(100),
            ind_pgto CHAR(1),
            vl_desc VARCHAR(100),
            vl_abat_nt VARCHAR(100),
            vl_merc VARCHAR(100),
            ind_frt CHAR(1),
            vl_frt VARCHAR(100),
            vl_seg VARCHAR(100),
            vl_out_da VARCHAR(100),
            vl_bc_icms VARCHAR(100),
            vl_icms VARCHAR(100),
            vl_bc_icms_st VARCHAR(100),
            vl_icms_st VARCHAR(100),
            vl_ipi VARCHAR(100),
            vl_pis VARCHAR(100),
            vl_cofins VARCHAR(100),
            vl_pis_st VARCHAR(100),
            vl_cofins_st VARCHAR(100),
            filial VARCHAR(4)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS c170 (
            id INT AUTO_INCREMENT PRIMARY KEY,
            periodo VARCHAR(10),
            reg CHAR(4) DEFAULT 'C170',
            num_item INT(3),
            cod_item VARCHAR(40),
            descr_compl VARCHAR(255),
            qtd VARCHAR(100),
            unid VARCHAR(6),
            vl_item VARCHAR(100),
            vl_desc VARCHAR(100),
            ind_mov CHAR(1),
            cst_icms VARCHAR(3),
            cfop VARCHAR(4),
            cod_nat VARCHAR(10),
            vl_bc_icms VARCHAR(100),
            aliq_icms VARCHAR(80),
            vl_icms VARCHAR(100),
            vl_bc_icms_st VARCHAR(100),
            aliq_st VARCHAR(100),
            vl_icms_st VARCHAR(100),
            ind_apur CHAR(1),
            cst_ipi CHAR(2),
            cod_enq CHAR(3),
            vl_bc_ipi VARCHAR(100),
            aliq_ipi VARCHAR(80),
            vl_ipi VARCHAR(100),
            cst_pis CHAR(2),
            vl_bc_pis VARCHAR(100),
            aliq_pis VARCHAR(80),
            quant_bc_pis VARCHAR(100),
            aliq_pis_reais VARCHAR(100),
            vl_pis VARCHAR(100),
            cst_cofins CHAR(2),
            vl_bc_cofins VARCHAR(100),
            aliq_cofins VARCHAR(80),
            quant_bc_cofins VARCHAR(100),
            aliq_cofins_reais VARCHAR(100),
            vl_cofins VARCHAR(100),
            cod_cta VARCHAR(100),
            vl_abat_nt VARCHAR(100),
            id_c100 INT,
            filial VARCHAR(4),
            ind_oper VARCHAR(1),
            cod_part VARCHAR(40),
            num_doc VARCHAR(9),
            chv_nfe VARCHAR(44),
            ncm VARCHAR(44) DEFAULT '',
            mercado VARCHAR(15) DEFAULT '',
            aliquota VARCHAR(10) DEFAULT '',
            resultado VARCHAR(100) DEFAULT '',
            FOREIGN KEY (id_c100) REFERENCES c100(id) ON DELETE CASCADE
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS `0200` (
            id INT AUTO_INCREMENT PRIMARY KEY,
            reg VARCHAR(4) DEFAULT '0200',
            cod_item VARCHAR(40) UNIQUE,
            descr_item VARCHAR(255),
            cod_barra VARCHAR(100),
            cod_ant_item VARCHAR(100),
            unid_inv VARCHAR(6),
            tipo_item VARCHAR(2),
            cod_ncm VARCHAR(8),
            ex_ipi VARCHAR(3),
            cod_gen VARCHAR(2),
            cod_list VARCHAR(5),
            aliq_icms VARCHAR(6),
            cest VARCHAR(7),
            periodo VARCHAR(10)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS `0150` (
            id INT AUTO_INCREMENT PRIMARY KEY,
            reg VARCHAR(4) DEFAULT '0150',
            cod_part VARCHAR(40) UNIQUE,
            nome VARCHAR(100),
            cod_pais VARCHAR(5),
            cnpj VARCHAR(20),
            cpf VARCHAR(11),
            ie VARCHAR(14),
            cod_mun VARCHAR(7),
            suframa VARCHAR(9),
            ende VARCHAR(100),
            num VARCHAR(10),
            compl VARCHAR(50),
            bairro VARCHAR(50),
            cod_uf VARCHAR(2),
            uf VARCHAR(2),
            pj_pf VARCHAR(2),
            periodo VARCHAR(10)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS cadastro_fornecedores (
            cod_part VARCHAR(40),
            nome VARCHAR(255),
            cnpj VARCHAR(14),
            uf VARCHAR(2),
            cnae VARCHAR(50),
            decreto VARCHAR(3),
            simples VARCHAR(3)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS c170nova (
            id INT AUTO_INCREMENT PRIMARY KEY,
            cod_item VARCHAR(40) UNIQUE,
            periodo VARCHAR(10),
            reg VARCHAR(20),
            num_item VARCHAR(50),
            descr_compl VARCHAR(255),
            cod_ncm VARCHAR(40),
            qtd VARCHAR(100),
            unid VARCHAR(30),
            vl_item VARCHAR(100),
            vl_desc DECIMAL(10,2),
            cfop VARCHAR(10),
            id_c100 VARCHAR(20),
            filial VARCHAR(10),
            ind_oper VARCHAR(1),
            cod_part VARCHAR(15),
            num_doc VARCHAR(50),
            chv_nfe VARCHAR(45)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS c170_clone (
            id_c170 INT PRIMARY KEY,
            periodo VARCHAR(10),
            reg CHAR(4) DEFAULT 'C170',
            num_item VARCHAR(3),
            cod_item VARCHAR(40),
            descr_compl VARCHAR(100),
            qtd VARCHAR(100),
            unid VARCHAR(6),
            vl_item VARCHAR(100),
            vl_desc DECIMAL(10,2),
            cfop VARCHAR(4),
            cst VARCHAR(3),
            ncm VARCHAR(40),
            id_c100 INT,
            filial VARCHAR(4),
            ind_oper VARCHAR(1),
            cod_part VARCHAR(40),
            num_doc VARCHAR(9),
            chv_nfe VARCHAR(44),
            aliquota VARCHAR(10),
            resultado DECIMAL(10,2),
            chavefinal VARCHAR(100) UNIQUE
        )
        """
    ]

    for sql in tabelas:
        cursor.execute(sql)
